=== alo7i/bioqrator/bioc/passage_relation.dtd
<!ELEMENT collection ( source, date, key, document+ ) >
<!ELEMENT source (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT key (#PCDATA)>

<!ELEMENT document ( id, passage+ ) >
<!ELEMENT id (#PCDATA)>

<!ELEMENT passage ( type, offset, annotation*, relation* ) >
<!ELEMENT type (#PCDATA)>
<!ELEMENT offset (#PCDATA)>

<!ELEMENT annotation ( type, location, text ) >
<!ATTLIST annotation id CDATA #IMPLIED >
<!ELEMENT location (#PCDATA)>
<!ELEMENT text (#PCDATA)>

<!ELEMENT relation ( type, label*, ref_id* ) >
<!ATTLIST relation id CDATA #IMPLIED >
<!ELEMENT label (#PCDATA)>
<!ELEMENT ref_id (#PCDATA)>

=== alo7i/bioqrator/bioc/bionlp_relations2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE collection SYSTEM "passage_relation.dtd">
<collection><source>bionlp09_shared_task_sample_data_rev3</source><date>20120921</date><key>bionlp.key</key><document><id>10485906</id><passage><type>title</type><offset>0</offset><annotation id="T33"><type>Negative_regulation</type><offset>12</offset><length>7</length><text>inhibit</text></annotation><annotation id="T34"><type>Positive_regulation</type><offset>20</offset><length>10</length><text>activation</text></annotation><annotation id="T35"><type>Positive_regulation</type><offset>79</offset><length>8</length><text>inducing</text></annotation><annotation id="T36"><type>Gene_expression</type><offset>100</offset><length>10</length><text>expression</text></annotation><relation id="E1"><type>Negative_regulation</type><label>Negative_regulation</label><label>Theme</label><label>Cause</label><ref_id>T33</ref_id><ref_id>E2</ref_id><ref_id>E3</ref_id></relation><relation id="E2"><type>Positive_regulation</type><label>Positive_regulation</label><label>Theme</label><label>Cause</label><ref_id>T34</ref_id><ref_id>T1</ref_id><ref_id>T2</ref_id></relation>

<relation id="E3"><type>Positive_regulation</type><label>Positive_regulation</label><label>Theme</label>

<ref_id>T35</ref_id><ref_id>E4</ref_id></relation>

<relation id="E4"><type>Gene_expression</type><label>Gene_expression</label><label>Theme</label><ref_id>T36</ref_id><ref_id>T3</ref_id></relation>


<relation id="M1"><type>Speculation</type><label>Speculation</label><ref_id>E12</ref_id></relation><relation id="M2"><type>Negation</type><label>Negation</label><ref_id>E14</ref_id></relation><relation id="M3"><type>Negation</type><label>Negation</label><ref_id>E15</ref_id></relation><relation id="M4"><type>Negation</type><label>Negation</label><ref_id>E18</ref_id></relation><relation id="M5"><type>Negation</type><label>Negation</label><ref_id>E19</ref_id></relation></passage><passage><type>abstract</type><offset>113</offset><annotation id="T37"><type>Positive_regulation</type><offset>313</offset><length>8</length><text>inducing</text></annotation><annotation id="T38"><type>Entity</type><offset>322</offset><length>8</length><text>tyrosine</text></annotation><annotation id="T39"><type>Phosphorylation</type><offset>331</offset><length>15</length><text>phosphorylation</text></annotation><annotation id="T40"><type>Binding</type><offset>348</offset><length>16</length><text>homodimerization</text></annotation><annotation id="T41"><type>Entity</type><offset>370</offset><length>7</length><text>nuclear</text></annotation><annotation id="T42"><type>Localization</type><offset>378</offset><length>13</length><text>translocation</text></annotation><annotation id="T43"><type>Positive_regulation</type><offset>601</offset><length>10</length><text>activation</text></annotation><annotation id="T44"><type>Regulation</type><offset>713</offset><length>8</length><text>regulate</text></annotation><annotation id="T45"><type>Positive_regulation</type><offset>722</offset><length>10</length><text>activation</text></annotation><annotation id="T46"><type>Negative_regulation</type><offset>981</offset><length>10</length><text>suppressed</text></annotation><annotation id="T47"><type>Positive_regulation</type><offset>992</offset><length>10</length><text>activation</text></annotation><annotation id="T48"><type>Negative_regulation</type><offset>1057</offset><length>9</length><text>decreased</text></annotation><annotation id="T49"><type>Entity</type><offset>1067</offset><length>8</length><text>tyrosine</text></annotation><annotation id="T50"><type>Phosphorylation</type><offset>1076</offset><length>15</length><text>phosphorylation</text></annotation><annotation id="T51"><type>Entity</type><offset>1096</offset><length>7</length><text>nuclear</text></annotation><annotation id="T52"><type>Localization</type><offset>1104</offset><length>13</length><text>translocation</text></annotation><annotation id="T53"><type>Positive_regulation</type><offset>1347</offset><length>9</length><text>induction</text></annotation><annotation id="T54"><type>Gene_expression</type><offset>1405</offset><length>10</length><text>expression</text></annotation><annotation id="T55"><type>Negative_regulation</type><offset>1628</offset><length>7</length><text>inhibit</text></annotation><annotation id="T56"><type>Positive_regulation</type><offset>1649</offset><length>10</length><text>activation</text></annotation><annotation id="T57"><type>Positive_regulation</type><offset>1727</offset><length>8</length><text>inducing</text></annotation><annotation id="T58"><type>Gene_expression</type><offset>1736</offset><length>10</length><text>expression</text></annotation><relation id="*0"><type>Equiv</type><label>Equiv</label><label>Equiv</label><ref_id>T6</ref_id><ref_id>T7</ref_id></relation><relation id="E5"><type>Positive_regulation</type><label>Positive_regulation</label><label>Theme</label><label>Cause</label><ref_id>T37</ref_id><ref_id>E10</ref_id><ref_id>T5</ref_id></relation><relation id="E6"><type>Positive_regulation</type><label>Positive_regulation</label><label>Theme</label><label>Cause</label><ref_id>T37</ref_id><ref_id>E9</ref_id><ref_id>T5</ref_id></relation><relation id="E7"><type>Positive_regulation</type><label>Positive_regulation</label><label>Theme</label><label>Cause</label><ref_id>T37</ref_id><ref_id>E8</ref_id><ref_id>T5</ref_id></relation><relation id="E8"><type>Phosphorylation</type><label>Phosphorylation</label><label>Theme</label><label>Site</label><ref_id>T39</ref_id><ref_id>T6</ref_id><ref_id>T38</ref_id></relation><relation id="E9"><type>Binding</type><label>Binding</label><label>Theme</label><ref_id>T40</ref_id><ref_id>T6</ref_id></relation><relation id="E10"><type>Localization</type><label>Localization</label><label>Theme</label><label>ToLoc</label><ref_id>T42</ref_id><ref_id>T6</ref_id><ref_id>T41</ref_id></relation><relation id="E11"><type>Positive_regulation</type><label>Positive_regulation</label><label>Theme</label><ref_id>T43</ref_id><ref_id>T10</ref_id></relation><relation id="E12"><type>Regulation</type><label>Regulation</label><label>Theme</label><ref_id>T44</ref_id><ref_id>E13</ref_id></relation><relation id="E13"><type>Positive_regulation</type><label>Positive_regulation</label><label>Theme</label><label>Cause</label><ref_id>T45</ref_id><ref_id>T12</ref_id><ref_id>T13</ref_id></relation><relation id="E14"><type>Negative_regulation</type><label>Negative_regulation</label><label>Theme</label><label>Cause</label><ref_id>T46</ref_id><ref_id>E20</ref_id><ref_id>T19</ref_id></relation><relation id="E15"><type>Negative_regulation</type><label>Negative_regulation</label><label>Theme</label><label>Cause</label><ref_id>T46</ref_id><ref_id>E20</ref_id><ref_id>T17</ref_id></relation><relation id="E16"><type>Negative_regulation</type><label>Negative_regulation</label><label>Theme</label><label>Cause</label><ref_id>T46</ref_id><ref_id>E20</ref_id><ref_id>T15</ref_id></relation><relation id="E17"><type>Negative_regulation</type><label>Negative_regulation</label><label>Theme</label><label>Cause</label><ref_id>T46</ref_id><ref_id>E20</ref_id><ref_id>T14</ref_id></relation><relation id="E18"><type>Negative_regulation</type><label>Negative_regulation</label><label>Theme</label><label>Cause</label><ref_id>T46</ref_id><ref_id>E20</ref_id><ref_id>T18</ref_id></relation><relation id="E19"><type>Negative_regulation</type><label>Negative_regulation</label><label>Theme</label><label>Cause</label><ref_id>T46</ref_id><ref_id>E20</ref_id><ref_id>T16</ref_id></relation><relation id="E20"><type>Positive_regulation</type><label>Positive_regulation</label><label>Theme</label><label>Cause</label><ref_id>T47</ref_id><ref_id>T20</ref_id><ref_id>T21</ref_id></relation><relation id="E21"><type>Negative_regulation</type><label>Negative_regulation</label><label>Theme</label><ref_id>T48</ref_id><ref_id>E23</ref_id></relation><relation id="E22"><type>Negative_regulation</type><label>Negative_regulation</label><label>Theme</label><ref_id>T48</ref_id><ref_id>E24</ref_id></relation><relation id="E23"><type>Phosphorylation</type><label>Phosphorylation</label><label>Theme</label><label>Site</label><ref_id>T50</ref_id><ref_id>T22</ref_id><ref_id>T49</ref_id></relation><relation id="E24"><type>Localization</type><label>Localization</label><label>Theme</label><label>ToLoc</label><ref_id>T52</ref_id><ref_id>T22</ref_id><ref_id>T51</ref_id></relation><relation id="E25"><type>Positive_regulation</type><label>Positive_regulation</label><label>Theme</label><ref_id>T53</ref_id><ref_id>T24</ref_id></relation><relation id="E26"><type>Gene_expression</type><label>Gene_expression</label><label>Theme</label><ref_id>T54</ref_id><ref_id>T25</ref_id></relation><relation id="E27"><type>Negative_regulation</type><label>Negative_regulation</label><label>Theme</label><label>Cause</label><ref_id>T55</ref_id><ref_id>E28</ref_id><ref_id>E29</ref_id></relation><relation id="E28"><type>Positive_regulation</type><label>Positive_regulation</label><label>Theme</label><label>Cause</label><ref_id>T56</ref_id><ref_id>T30</ref_id><ref_id>T29</ref_id></relation><relation id="E29"><type>Positive_regulation</type><label>Positive_regulation</label><label>Theme</label><ref_id>T57</ref_id><ref_id>E30</ref_id></relation><relation id="E30"><type>Gene_expression</type><label>Gene_expression</label><label>Theme</label><ref_id>T58</ref_id><ref_id>T32</ref_id></relation></passage></document>




</collection>
